.github/workflows/dev.yml

Fixed the GitHub workflow syntax

fixed workflow synthax error

---

.github/workflows/dev.yml

I corrected the Runner typo "self-hosted"

Corrected runner label

---

.github/workflows/dev.yml
server-script/aihomeworkdev.service
server-script/startappdev.sh

Added the systemd config

---

.github/workflows/dev.yml

Corrected the daemon typo

---

.github/workflows/dev.yml

corrected system typos

---

.github/workflows/dev.yml

Added test to dev.yml file

---

.github/workflows/dev.yml

added tag for test to pass

---

.github/workflows/dev.yml

Made corrections to the dev.yml run test step

---

package.json

updated typescript version

---

.github/workflows/dev.yml

Update dev.yml; stash before pull

---

src/controllers/NotificationController.ts
src/controllers/index.ts
src/index.ts
src/routes/index.ts
src/routes/notificationsettings.ts

My PR Closes #19
> Implemented a backend code for setting a users notification's status

Feat/19 Implement Backend for Notification Settings

---

package.json
src/config/index.ts
src/controllers/SmsController.ts
src/index.ts
src/routes/index.ts
src/routes/sms.ts
src/services/sms.services.ts
yarn.lock

[feat] send sms via Twilio API

---

src/controllers/TestimonialsController.ts
src/routes/testimonial.ts

ADDED CONTROLLER AND ROUTES PATH TO PROVIDE ENDPOINT FOR GETTING AL TESTIMONIALS AND DELETING SINGLE TESTIMONIAL

---

.github/workflows/prod.yml
server-script/startappprod.sh

new changes added to server-script

---

.github/workflows/dev.yml
.github/workflows/pr.yml

Corrected the branch of dev CI/CD pipeline

---

src/controllers/jobController.ts
src/index.ts
src/models/index.ts
src/models/job.ts
src/routes/index.ts
src/routes/job.ts
src/services/job.service.ts

Description
_Implement a feature to create a new job listing in the database. This endpoint should allow users to submit job details and store them in the system. Upon successful creation, it will return the newly created job listing details with a '201' status. If an error occurs, an appropriate error status will be returned._
Acceptance Criteria
- The endpoint allows an authenticated user to create a new job listing in the database.
- Returns a 201 status code and the correct response body when the job listing is created successfully.
- Returns a 400 status code and the correct response body when the request data is invalid.
- Returns a 401 status code and the user is not authenticated
- Returns an appropriate error message when an error occurs.
Requirements
- Implement API endpoint for …

FEAT] Add API Endpoint to Create New Job Listings #54

---

server-script/startappprod.sh
udo yarn global add pnpm

changes added to deployment workflow for prod

---

src/controllers/ProductController.ts
src/data-source.ts
src/models/product.ts
src/routes/product.ts
src/services/index.ts
src/services/product.services.ts

Develop an API endpoint to list products with pagination support. The endpoint should return basic information about each product, including the product name, price, and category.
1. API Endpoint: Create an endpoint /api/v1/products.
2. Response Structure: The response should include:
- Product name
- Product price
- Product category
3. Pagination Support: Include pagination parameters in the request:
- page: Current page number (default is 1)
- limit: Number of products per page (default is 10)
4. Response Pagination Info: Include pagination information in the response:
- totalItems: Total number of products
- totalPages: Total number of pages
- currentPage: Current page number
To provide a means for clients to retrieve a paginated list of products with essential details, enhancing the …

fit list products

---

src/middleware/checkUserRole.ts

Description
fixed the user permission middleware and and the merge conflict
>

fix: fixed the user permission middleware and and the merge conflict

---

src/models/blog.ts

update oblog schema

---

server-script/startappdev.sh
server-script/startappprod.sh

Make the startappprod executable

---

src/controllers/UserController.ts
src/models/user.ts
src/routes/user.ts
src/services/user.services.ts
src/test/users.spec.ts

This pull request addresses the login feature implementation as per issue #9 
> - Github Issue Example: My PR Closes #128
> - Linear Ticket Example: Fixes ID-128
- Implement an API endpoint feature to perform a soft delete on a user.
- Added route handling in routes/users.ts for the /users/:id endpoint.
- The `deleted_at` timestamp and `is_deleted` property was added to the user entity.
- Protected the routes using middleware to prevent unauthorized access.
- Added tests for the userService in the users.spec.ts file.

[FEAT]: API Endpoint To Perform a Soft Delete on a User #128

---

src/controllers/UserController.ts
src/test/user.spec.ts

- Added view user profile endpoint

Feat/#120 Implements API endpoint for retrieving the profile data of the currently authenticated user

---

package.json
src/controllers/AdminController.ts
src/routes/admin.ts
src/routes/user.ts
src/services/admin.services.ts
src/utils/index.ts
yarn.lock

resolved bot issue and added ListUser with pagination(SuperAdmin) functionallity

---

src/index.ts
src/services/blog.services.ts
yarn.lock

Chore: Rate limiter for all route

---

src/index.ts

fix: updated limiter to run before all route

---

src/controllers/createorgController.ts
yarn.lock

feat: organisation endpoint documentation

---

src/controllers/AuthController.ts
src/controllers/updateBlogController.ts
src/routes/blog.ts
src/services/updateBlog.services.ts

docs(auth): add API documentation for forget and reset password
>

docs(auth): add API documentation for forget and reset password

---

src/controllers/AdminController.ts
src/models/index.ts
src/models/log.ts
src/routes/admin.ts
src/services/admin.services.ts

> - Github Issue: [Link to Issue](https://github.com/hngprojects/hng_boilerplate_expressjs/issues/155)
> This endpoint enables authenticated super admins to retrieve logs of activities.
> Access is restricted to users with super admin privileges to ensure system security.

feat: super admin gets logs of activities

---

docs/sendEmail.md
package.json
src/controllers/NotificationController.ts
src/controllers/ProductController.ts
src/controllers/exportController.ts
src/controllers/updateBlogController.ts
src/index.ts
src/middleware/testimonial.validation.ts
src/services/admin.services.ts
src/services/blog.services.ts
src/services/help.services.ts
src/services/sendEmail.services.ts
src/services/updateBlog.services.ts

fix: fixed asynchronous operations while runing test

---

src/controllers/AuthController.ts
src/routes/auth.ts
src/services/auth.services.ts
src/test/auth.spec.ts
src/types/index.d.ts

Feat authentication/update user password

---

src/routes/auth.ts

chore: switched routes to kebab case

---

src/controllers/updateorgController.ts
src/index.ts

feat: Endpoint to update organisation details  

---

src/routes/admin.ts

> - Github Issue: [Link to Issue](https://github.com/hngprojects/hng_boilerplate_expressjs/issues/155)
>Initial PR already merged, made slight modifications to the route for the endpoint.
> This endpoint enables authenticated super admins to retrieve logs of activities.
> Access is restricted to users with super admin privileges to ensure system security.

feat: super admin gets log of activities

---

src/controllers/sendEmail.controller.ts
src/schema/emailTemplate.ts

docs(email): swagger documentation for email-routes

---

docs/blog.md
src/routes/blog.ts

>
> - Github Issue Example: My PR Closes #159

feat: docs blog routes

---

src/routes/user.ts

**Title:**
`feat(users): added swagger docs for all users route`
**Changes:**
- Documentation for Users route.

feat(users): added swagger docs for all users route

---

src/controllers/OrgController.ts
src/services/sms.services.ts

feat: create org docs

---

src/controllers/PaymentLemonSqueezyController.ts

>
> - Github Issue Example: My PR Closes #134 
Added Swagger documentation for LemonSqueezy payment endpoints.

docs: Add LemonSqueezy payment docs

---

src/controllers/OrgController.ts

>
> -  My Previous PR  #180 
> -  Issue Worked On #125 
> Correct swagger docs on `orgController.ts` folder

fix(docs):  correct Swagger documentation for Organisations Endpoint

---

src/controllers/OrgController.ts
src/routes/organisation.ts
src/services/org.services.ts

[fix]: organisation Docs and Endpoint

---

src/middleware/auth.ts
src/services/user.services.ts

Fix: Fixed Auth Middleware

---

src/controllers/HelpController.ts
src/routes/help-center.ts
src/services/help.services.ts
src/test/help-center.spec.ts

>
> - Github Issue Example: My PR Closes #328  
> - Linear Ticket Example: Fixes ID-#328
> - Updated help.service.ts
> - Updated help.controller.ts
> - Created tests for  getTopicById endpoints

[FEAT]: API Endpoint to Get a Help Center Topic by ID

---

src/controllers/HelpController.ts
src/routes/help-center.ts
src/services/help.services.ts

>
> - Github Issue Example: My PR Closes #327  
> - Linear Ticket Example: Fixes ID-#327
> - Updated help.service.ts
> - Updated help.controller.ts
> - Created tests for  deleteTopic endpoints
> - Added documentation for Help Center

[FEAT]: API Endpoint to Delete a Help Center Topic by ID

---

src/controllers/sendEmail.controller.ts
src/services/org.services.ts
src/services/sendEmail.services.ts
src/test/createInviteToOrg.spec.ts
src/utils/emailVariables.ts
yarn.lock

feat: added invitation email message to invite user to organisation

---

.husky/pre-commit
src/data-source.ts
src/index.ts

chore: hng-test

---

src/data-source.ts
src/index.ts

feat: test route

---

src/controllers/contactController.ts

fix: endpoint convension

---

.github/workflows/dev.yml

fix: fix on ci/cd

---

src/controllers/contactController.ts
src/data-source.ts
src/index.ts

fix: change contact-us route

---

src/controllers/AuthController.ts

fix: social auth

---

src/controllers/FaqController.ts
src/controllers/index.ts
src/index.ts
src/models/faq.ts
src/models/index.ts
src/routes/faq.ts
src/routes/index.ts
src/services/faq.services.ts
src/services/index.ts

> This endpoint retrieves all FAQ in the database

Feat: API Endpoint to retrieve all FAQ

---

src/index.ts
src/services/auth.services.ts

fix: auth token timer

---

src/controllers/exportController.ts
src/services/export.services.ts

> update services and controller  file to use async instead of sync

fix: export user data async

---

src/services/auth.services.ts

fix: update auth.services.ts

---

src/controllers/HelpController.ts
src/routes/help-center.ts

>
> Fixed the issue with creating help center topics and the responses returned by the server

fix: Create Help Center Topic

---

src/index.ts

chore: update index.ts

---

src/controllers/AuthController.ts
src/index.ts
src/services/auth.services.ts
src/test/auth.spec.ts
src/test/superadminUpdateOrg.spec.ts

fix: authentication documentation

---

src/controllers/NotificationController.ts
src/controllers/roleController.ts
src/index.ts
src/models/notification.ts
src/routes/notificationsettings.ts
src/routes/roles.ts
src/services/role.services.ts
src/test/roles.spec.ts

feat: Add user role endpoint

---

src/index.ts
src/utils/request-body-validator.ts

fix: validate magic link request body 

---

src/controllers/UserController.ts

refactor: updated documentation for update user endpoint

---

src/app.ts
src/controllers/admincontroller.ts
src/controllers/index.ts
src/routes/admin.ts
src/routes/index.ts
src/services/adminservice.ts
src/services/index.ts

>
> Changes in the admin file of the project

feat: admin files

---

src/app.ts
src/config/index.ts
src/controllers/emailcontroller.ts
src/controllers/index.ts
src/models/emailQueue.ts
src/models/index.ts
src/routes/email.ts
src/routes/index.ts
src/schemas/email.ts
src/services/emailservice.ts
src/services/index.ts
src/types/index.ts
src/utils/queue.ts
src/utils/sms.ts
src/views/bull-board.ts

feat: set up messaging queue

---

src/controllers/admincontroller.ts
src/middleware/checkUserRole.ts
src/models/organization.ts
src/models/user-organization.ts
src/models/user.ts
src/routes/admin.ts
src/schemas/organization.ts
src/services/adminservice.ts
src/test/superadminOrg.spec.ts

>
> - Github Issue Example: My PR Closes #238 
> - Linear Ticket Example: Fixes ID-#238

feat: update and delete organisation by superadmin

---

src/app.ts
src/controllers/index.ts
src/controllers/organizationcontroller.ts
src/routes/index.ts
src/routes/organization.ts
src/services/index.ts
src/services/organizationservice.ts

>
> This PR introduces an endpoint for organization to export user data

feat: organization - export-data

---

src/controllers/admincontroller.ts
src/routes/admin.ts
src/services/adminservice.ts

feat: superadmin update and delete organisation

---

src/app.ts
src/controllers/contactcontroller.ts
src/controllers/index.ts
src/models/contact.ts
src/models/index.ts
src/routes/contact.ts
src/routes/index.ts
src/schemas/contact.ts
src/services/contactservice.ts
src/services/index.ts
src/test/contact.spec.ts

>
> This PR introduces an endpoint for creating contact us

feat: contact us

---

src/controllers/admincontroller.ts
src/controllers/notificationSettingController.ts
src/controllers/notificationsController.ts

>
- Added Swagger documentation for the following endpoints:
-  Included detailed descriptions, request parameters, and response schemas for each endpoint.
- Updated the Swagger configuration to include the new documentation.

docs(api): add Swagger docs for notifications

---

src/controllers/UserController.ts
src/routes/user.ts
src/services/userservice.ts
src/test/user.spec.ts

>
- add user tests
- refactor route, service, controller
- updated docs

fix: add user tests, refactor service, controller, and update doc

---

src/controllers/index.ts
src/controllers/inviteController.ts
src/enums/UserType.ts
src/models/index.ts
src/models/invitation.ts
src/routes/index.ts
src/routes/invite.ts
src/services/index.ts
src/services/inviteService.ts
src/test/invitation.spec.ts

feat: generate organisation invite link

---

src/controllers/SqueezeController.ts
src/controllers/UserController.ts
src/data-source.ts
src/routes/squeeze.ts
src/routes/user.ts
src/test/squeeze.spec.ts
src/test/user.spec.ts

- controllers/SqueezeController.ts
- controllers/UserController.ts
- routes/squeeze.ts
- routes/user.ts
- test/squeeze.spec.ts
- test/user.spec.ts

fix: add more test, refactor user and squeeze

---

src/controllers/ProductController.ts
src/middleware/organization.validation.ts
src/routes/product.ts
src/services/org.services.ts
src/services/product.services.ts
src/test/product.spec.ts

fix: product creation, deletion, and search functionalities

---

.gitignore
src/controllers/OrgController.ts
src/enums/permission-category.enum.ts
src/models/organization-member.ts
src/models/organization-role.entity.ts
src/models/organization.ts
src/models/permissions.entity.ts
src/models/user.ts
src/routes/organisation.ts
src/services/org.services.ts
src/services/user.services.ts
src/test/blog.spec.ts
src/test/organisation.spec.ts
src/test/users.spec.ts

>
> - Linear Ticket Example: Fixes ID-#BBE-55

feat: get all roles in organisation

---

src/controllers/AuthController.ts
src/routes/auth.ts

fix: verify magic link

---

src/controllers/FaqController.ts
src/routes/faq.ts
src/services/faq.services.ts

feat: get all faq

---

src/controllers/NewsLetterSubscriptionController.ts
src/controllers/OrgController.ts
src/schema/newsletterschema.ts
src/schema/organization.schema.ts

feat: api docs

---

src/controllers/AuthController.ts
src/routes/auth.ts
src/services/auth.services.ts

feat: verify 2fa

---

src/controllers/jobController.ts
src/test/jobs.spec.ts

fix(job): wrote test for get all jobs

---

.github/workflows/dev.yml
.github/workflows/staging.yml
docker-compose.production.yml
docker-compose.staging.yml
docker-compose.yml
server-script/aihomeworkstaging.service
server-script/startappstaging.sh

rewrite dev.yml file to build with docker

rewrite dev.yml file 

---

src/models/faq.ts
src/models/user.ts

Feat user table

---

.github/workflows/dev.yml
.github/workflows/prod.yml
.github/workflows/staging.yml
docker-compose.production.yml
docker-compose.staging.yml

Updated docker-compose files: Changed service names 
Updated  workflows

updated dockercompose files and workflows

---

src/controllers/planController.ts
src/index.ts
src/middleware/authorisationSuperAdmin.ts
src/models/plan.ts
src/models/subcription.ts
src/models/user.ts
src/routes/plans.ts
src/services/super-admin-plans.ts

feat: implement API endpoints for managing user plans by super admin

---

src/controllers/planController.ts

fix: update documentation
